### ISSUE TITLE
Feil: .jackson.annotation is not visible

### ISSUE THREAD

**Issue by kuvi14** [statisticsnorway/guardian-client-java#3]
Mulig feil: ...jackson.annotation is not visible

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project guardian-client: Compilation failure
[ERROR] ../guardian-client-java-master/src/main/java/no/ssb/guardian/client/Util.java:[3,29] package com.fasterxml.jackson.annotation is not visible
[ERROR]   (package com.fasterxml.jackson.annotation is declared in module com.fasterxml.jackson.databind, which does not export it)

**Mulig fiks?**

module-info.java
..
 module no.ssb.guardian.client {
    requires com.fasterxml.jackson.annotation;  <-- tilføyd

og bygger fint etterpå

mvh .kurt

**Comment by kschulst** [comment]
Closed by https://github.com/statisticsnorway/guardian-client-java/pull/4
